-- Default (enUS) locale for LFG Spyglass. GENERATED by tests/gen_locale.py from the L["..."] keys in
-- the code; edit the code, then re-run the script.
-- Rule: reuse Blizzard GlobalStrings (TANK, HEALER, DAMAGER, SIGN_UP, RESET, class names, ...)
-- wherever one exists; only add keys for text Blizzard does not already provide.
-- Keys are the English text itself (value `true`), so missing translations fall back to enUS.
local L = LibStub("AceLocale-3.0"):NewLocale((...), "enUS", true) -- the add-on folder name (also the dev copy)
if not L then return end


-- Core/Init.lua
L["%s is also loaded. Results may be filtered by both addons; consider using one filter at a time."] = true

-- Data/LeaderProgress.lua
L["N"] = true
L["H"] = true
L["M"] = true

-- UI/FilterPanel.lua
L["in combat"] = true
L["encounter"] = true
L["Mythic+"] = true
L["PvP"] = true
L["restricted"] = true
L["Party fit"] = true
L["Has a Tank"] = true
L["Has a Healer"] = true
L["Not Declined"] = true
L["Bloodlust"] = true
L["Hide Class"] = true
L["Battle Res"] = true
L["Hide groups without an open spot for your role, or, in a party, for every member's role."] = true
L["Show only groups that already have a tank."] = true
L["Show only groups that already have a healer."] = true
L["Hide groups that have declined your application."] = true
L["Hide groups that already have a Shaman, Mage, Evoker or Hunter."] = true
L["Hide groups that already have someone of your class."] = true
L["Hide groups that already have a Druid, Death Knight, Warlock or Paladin."] = true
L["Blizzard order"] = true
L["Sort"] = true
L["Settings"] = true
L["Reset all"] = true
L["Clear this category's filters and sort, and sign up as your spec's role again."] = true
L["Selected: only the selected dungeons are shown."] = true
L["Excluded: this dungeon's groups are hidden."] = true
L["Left-click: show only selected dungeons. Right-click: hide this dungeon. Click again to clear."] = true
L["Only groups that haven't killed this boss yet."] = true
L["Only groups that have already killed this boss."] = true
L["Left-click: still alive. Right-click: already dead. Click again to clear."] = true
L["DPS"] = true
L["Your class can't play this role."] = true
L["Roles you sign up as: pre-ticked in Blizzard's sign-up dialog and used by Party fit. Default: your spec's role."] = true
L["Dungeons"] = true
L["All"] = true
L["Select all (same as none: all groups shown)."] = true
L["None"] = true
L["Clear the selection and the exclusions (all groups shown)."] = true
L["Difficulty"] = true
L["Bosses"] = true
L["Boss list not available yet"] = true
L["Clear the boss marks."] = true
L["Fresh run"] = true
L["Only groups with no bosses defeated yet."] = true
L["Members"] = true
L["min"] = true
L["max"] = true
L["Most tanks"] = true
L["Most healers"] = true
L["Ranges"] = true
L["Leader rating"] = true
L["Only leaders rated %d or more."] = true
L["Group needs"] = true
L["I sign up as"] = true
L["Bosses (%s)"] = true
L["Dungeon list not available yet"] = true
L["Nothing matches"] = true
L["1 group matches"] = true
L["%d groups match"] = true
L["Filters paused (%s)"] = true
L["Filter error: showing all groups"] = true
L["Filter off"] = true
L["Leader rating (high to low)"] = true
L["Newest listings first"] = true
L["Most members"] = true
L["Leader progress (high to low)"] = true
L["Show leader rating"] = true
L["Show the group leader's Mythic+ rating on each group."] = true
L["Show region"] = true
L["Show the group leader's region (flag and tag, for example East or DE) on each group."] = true
L["Show spec role"] = true
L["Show each member's spec icon with a role badge instead of Blizzard's class icons. Off: Blizzard's default icons."] = true
L["Show who's leader"] = true
L["Show a crown on the group leader's icon."] = true
L["Show leader progress"] = true
L["Show the raid leader's progress in that raid (and their main's, if better) from Raider.IO. Needs Raider.IO."] = true
L["Show ranges"] = true
L["Show the Ranges section (Dungeons: leader rating; Raids: members, most tanks and healers). Off: the section is hidden and those ranges don't filter; your values come back when you turn it on again."] = true
L["Normal"] = true
L["Heroic"] = true
L["Mythic"] = true

-- UI/ResultList.lua
L["main"] = true

-- UI/ToggleButton.lua
L["LFG Spyglass filter: on"] = true
L["LFG Spyglass filter: off"] = true
L["Click to turn the filter off and show the stock Group Finder."] = true
L["Click to turn the filter on."] = true
